// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/LiveControls.tsx";
import * as $$$0 from "./sections/main.tsx";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: { "./islands/LiveControls.tsx": $$0 },
  sections: { "./sections/main.tsx": $$$0 },
  functions: {},
  schemas: {
    "./sections/main.tsx": {
      "inputSchema": {
        "title": "Main",
        "type": "object",
        "properties": {
          "img": {
            "format": "image-uri",
            "type": "string",
            "title": "Img",
          },
          "profileImg": {
            "format": "image-uri",
            "type": "string",
            "title": "Profile Img",
          },
          "listaLink": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string",
                  "title": "Url",
                },
                "titulo": {
                  "type": "string",
                  "title": "Titulo",
                },
              },
              "required": [
                "url",
                "titulo",
              ],
            },
            "title": "Lista Link",
          },
          "titulo": {
            "type": "string",
            "title": "Titulo",
          },
          "subtitulo": {
            "type": "string",
            "title": "Subtitulo",
          },
        },
        "required": [
          "img",
          "profileImg",
          "listaLink",
          "titulo",
        ],
      },
      "outputSchema": null,
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
globalThis.manifest = manifest;

export default manifest;
